SELECT COUNT(*)
FROM EMPLOYEE;

INSERT INTO EMPLOYEE VALUES( 21, 'Mary', 'P', 'Doe', '1978-01-13', 15, 'Station St.', 'Horsley', 'NSW', 2530 );

SELECT TNUM, COUNT(*)
FROM TRIPLEG
HAVING COUNT(*) > 10;

INSERT INTO EMPLOYEE VALUES( 22, 'Janusz', 'R', 'Getta', '1916-01-01', 10, 'Ellenborough Pl.', 'Horsley', 'NSW', 2530 );

INSERT INTO EMPLOYEE VALUES( 22, 'Janusz', 'R', 'Getta', '1916-01-01', 10, 'Ellenborough Pl.', 'Horsley', 'NSW', 2530 );

SELECT REGNUM, CAPACITY, STATUS
FROM TRUCK
WHERE CAPACITY BETWEEN 2000 AND 4000;

UPDATE TRIPLEG
SET DEPARTURE = 'Perth'
WHERE DEPARTURE = 'PERTH';

INSERT INTO ADMIN VALUES( 21, 'PROGRAMMER' );
INSERT INTO ADMIN VALUES( 22, 'DBA' );

DELETE FROM ADMIN WHERE ENUM = 20;

SELECT FNAME, LNAME
FROM EMPLOYEE
WHERE STATE = 'NSW' AND( upper(SUBURB) = 'HURSTVILLE' AND upper(STREET) = 'VICTORIA ST.' OR upper(SUBURB) = 'PENNANT HILLS' );

DELETE FROM EMPLOYEE WHERE ENUM = 20;

UPDATE ADMIN SET POSITION = 'BOSS' WHERE ENUM =  18;

SELECT REGNUM
FROM TRUCK 
ORDER BY STATUS ASC, REGNUM DESC;

SELECT COUNT(DISTINCT DEPARTURE)
FROM TRIPLEG
WHERE LEGNUM = 1;

CREATE TABLE MESSAGE( mbody VARCHAR(25), CONSTRAINT MESSAGE_PKEY PRIMARY KEY (mbody) );

SELECT LNUM, COUNT(*)
FROM TRIP
GROUP BY LNUM;

INSERT INTO MESSAGE( 'Hello world !!!' );
COMMIT;

INSERT INTO EMPLOYEE VALUES( 02, 'Janusz', 'R', 'Getta', '1916-01-01', 10, 'Ellenborough Pl.', 'Horsley', 'NSW', 2530 );

SELECT REGNUM, COUNT(*)
FROM TRIP
GROUP BY REGNUM
WHERE COUNT(*) > 5;

SELECT FNAME, LNAME
FROM EMPLOYEE
WHERE INITIALS IS NULL AND DOB IS NOT NULL;

ALTER TABLE MESSAGE MODIFY mbody VARCHAR(50);

SELECT FNAME, LNAME
FROM EMPLOYEE
WHERE INITIALS IS NULL AND DOB IS NOT NULL;

UPDATE MESSAGE SET mbody = 'Hello myworld !!!' WHERE mbody LIKE 'Hello%';

SELECT TNUM, LNUM, REGNUM
FROM TRIP
WHERE TDATE > '2016-02-01' AND TDATE <= DATE_ADD('2016-02-01', INTERVAL 30 DAY);

ROLLBACK;

DELETE FROM ADMIN WHERE ENUM < 18;

DROP TABLE MESSAGE;

COMMIT;

SELECT COUNT(DISTINCT TNUM)
FROM TRIPLEG
WHERE DEPARTURE LIKE '%y%' OR DESTINATION LIKE '%y%';

SELECT COUNT(*)
FROM EMPLOYEE

INSERT INTO EMPLOYEE VALUES( 21, 'Mary', 'P', 'Doe', '1978-01-13', 15, 'Station St.', 'Horsley', 'NSW', 2530 );

SELECT TNUM, COUNT(*)
FROM TRIPLEG
GROUP BY TNUM
HAVING COUNT(*) > 10;

INSERT INTO EMPLOYEE VALUES( 22, 'Janusz', 'R', 'Getta', '1916-01-01', 10, 'Ellenborough Pl.', 'Horsley', 'NSW', 2530 );

INSERT INTO EMPLOYEE VALUES( 22, 'Janusz', 'R', 'Getta', '1916-01-01', 10, 'Ellenborough Pl.', 'Horsley', 'NSW', 2530 );

SELECT *
FROM TRUCK
WHERE CAPACITY BETWEEN 2000 AND 4000;
