[Variables]
Author=Evans Stenakis
Name=Variables
Version=Summer 2020
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0



;;UserImagePath=#@#Particles\User\Icon.jpg
;;UserName=%username%
UserImagePath=C:\Users\ervan\Desktop\New Logo.jpg
UserName=Zoofie

MorningWP=#@#Wallpapers\Morning.jpg
NoonWP=#@#Wallpapers\Noon.jpg
AfternoonWP=#@#Wallpapers\Afternoon.jpg
EveningWP=#@#Wallpapers\Evening.jpg
NightWP=#@#Wallpapers\Night.jpg

MorningHour=06
NoonHour=12
AfternoonHour=16
EveningHour=20
NightHour=23

MusicFont=Ukij Qolyazma
DateFont=Lemon/Milk Light
ClockFont=Beckman Free
UserFont=Beckman Free

Morning=Good Morning
Noon=Good Noon
Afternoon=Good Afternoon
Evening=Good Evening
Night=Good Night

AudioPlayerName=Spotify
Icon1Path=C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Icon1Name=chrome.png


Icon1Path=C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Icon2Path=3
Icon3Path=3
Icon4Path=3
Icon6Path=3
Icon7Path=3
Icon8Path=3
Icon9Path=3

Icon1Name=chrome.png
Icon2Name=3
Icon3Name=3
Icon4Name=3
Icon6Name=3
Icon7Name=3
Icon8Name=3
Icon9Name=3

Music=NowPlaying.dll

Language=en-US
ClipString=768
Accent=136,51,110
